### ISSUE TITLE
Xamarin android 5.1 changes

### ISSUE THREAD

**Issue by omares** [jamesathey/FastAndroidCamera#3]
Hey,

does the [xamarin android 5.1 change regarding JNIEnv](http://developer.xamarin.com/releases/android/xamarin.android_5/xamarin.android_5.1/#GC-free_Method_Invocations) have any effects on the library?

Is there a need to make changes to the library to utilize the new GC feature?

**Comment by jamesathey** [comment]
@omares There is no _need_ to make changes, as Xamarin 5.1 still has the old params JValue[] interfaces in JNIEnv. Using the new JValue\* overloads would make this project incompatible with previous versions of Xamarin, but that may not be a big concern, as I imagine most Xamarin customers allow updates from the Stable channel to install.

There are only three or four places where the new JValue\* overloads could be used (all within CameraExtensions), and doing so would relieve a small amount of GC pressure. In the apps you and I work with, there are two invocations of `JNIEnv.CallVoidMethod()` per preview frame: one call to `Camera.AddCallbackBuffer()`, and one call to the callback itself via the callback invoker.
