### ISSUE TITLE
[libc] Fatal signal 6

### ISSUE THREAD

**Issue by mgamache** [jamesathey/FastAndroidCamera#4]
I am trying to get a simple sample project running using the FastAndroidCamera, but after ~990 frames (@ 30fps) my app crashes with:

> [libc] Fatal signal 6 (SIGABRT) at 0x0000179c (code=-6)

I've tried to follow your sample code closely. Here's my callback code:

``` c#
public void OnPreviewFrame(IntPtr data, Android.Hardware.Camera camera)
        {
        totalFrames++;
        FastJavaByteArray buffer = new FastJavaByteArray(data);
        Console.WriteLine ("frame " + totalFrames );
        camera.AddCallbackBuffer(buffer);
        }
```
- The memory usage seems to be pretty stable (no leaks);
- Does not change with number of buffers (used 30 and 90)
- Running Android 4.4 on Intel x86 based hardware.
- Cpu is 40% idle

not sure what to change?

**Comment by jamesathey** [comment]
I've updated the documentation to encourage users of the library to wrap instances of FastJavaByteArray in using() blocks. That ensures that the Java references get released when they should. Take a look at the revised sample code and let me know if doing it that way solves your problem.

**Comment by mgamache** [comment]
Thanks I’ll give that a shot.
