### ISSUE TITLE
Null Exception in JniEnvEx

### ISSUE THREAD

**Issue by mgamache** [jamesathey/FastAndroidCamera#5]
in the class JniEnvEx

getting a null returned with the following call:
`
var envP = typeof(JNIEnv).GetProperty ("Env", BindingFlags.NonPublic | BindingFlags.Static);`

_here's the method:_

```
static void GetDelegate<TDelegate> (string name, ref TDelegate value)
            where TDelegate : class
        {
            if (value != null)
                return;
//////this line returns null....
            var envP = typeof(JNIEnv).GetProperty ("Env", BindingFlags.NonPublic | BindingFlags.Static);
/////
            var env = envP.GetValue (null);
            var JniEnvP = env.GetType ().GetField ("JniEnv", BindingFlags.NonPublic | BindingFlags.Instance);
            var JniEnv = JniEnvP.GetValue (env);
            var d = JniEnv.GetType ().GetField (name);
            value = (TDelegate) (object) Marshal.GetDelegateForFunctionPointer ((IntPtr) d.GetValue (JniEnv), typeof (TDelegate));
        }
```

does this have something to do with Xamarin changes? I may try and roll back to an earlier version.

**Comment by mgamache** [comment]
FYI... Rolling back to 6.0.4.0 fixed this issue for me.

**Comment by jamesathey** [comment]
@matomato13 FastAndroidCamera should now work with the latest stable Xamarin.Android. It will not work with older Xamarin.Android releases anymore, unfortunately. [Try the 2.0 release, available from NuGet](https://www.nuget.org/packages/FastAndroidCamera/2.0.0), and let me know if I can close this issue.

**Comment by matomato13** [comment]
@jamesathey Just tested it and it works.  Did you keep the CameraExtensions class for reference?

**Comment by jamesathey** [comment]
@matomato13 CameraExtensions is where the SetNonMarshalingPreviewCallback() additions to Android.Hardware.Camera live. It was not obsoleted. Did you mean JniEnvEx? That class was removed.

**Comment by matomato13** [comment]
@jamesathey Nevermind my comment, you're right I mixed them both since I saw JniEnv being called.
